spring.application.name=budget-edit-app
server.port=8082

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/mint}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:mint}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:mint}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
